name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm install
      working-direcotry: project-1/chat-app-vue
      
    - run: npm run build --if-present
      working-direcotry: project-1/chat-app-vue
      
    - run: npm test
      working-direcotry: project-1/chat-app-vue
      env:
        CI: true
