name: Live Coding 9 Projetos Front-End

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Executando o C.I & C.D no project-1    
    - run: npm install
      working-directory: ./project-1/chat-app-vue
      
    # Executando o C.I & C.D no project-2
    - run: node main
      working-directory: ./project-2
      
      env:
        CI: true
